.github/workflows/cffconvert.yaml, .github/workflows/cffconvert.yml, CITATION.cff
This Pull Requests introduces initial citation meta data for this project using the [Citation File Format](https://github.com/citation-file-format/citation-file-format) standard.  I also added the automatic validator such that one can rely on the correctness of the configuration file.
The introduced citation meta data are rendered by GitHub to a "Cite this repository" option on this project's welcome page.  People interested in this project can then cite it in their papers and theses.
The meta data can be freely enriched with further fields as required.  Furthermore, there is the option to add a list of references to it.  This way, you can cite the used resources in order to create this project.
Please tell me whether the suggested initial meta data set is correct and if I should add …
=> [Enhancement] Add Citation Meta Data

.github/workflows/CI.yaml, .github/workflows/actionlint.yaml, .github/workflows/cffconvert.yaml, CHANGELOG.adoc, CITATION.cff, examples/cat.rs, examples/cmp.rs, examples/isutf8.rs, justfile, src/error.rs, src/exit_code.rs, src/lib.rs
Change the comment header to the format recommended by the REUSE Specification.[^1]
[^1]: https://reuse.software/spec/#comment-headers
=> Update copyright notice

CHANGELOG.adoc, src/exit_code.rs
Supports all primitive integer types.
=> Add more conversions to primitive integer types

.bumpversion.cfg, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.6

.bumpversion.cfg, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.7

CHANGELOG.adoc, LICENSES/MIT.txt, README.md, examples/cat.rs, examples/cmp.rs, examples/isutf8.rs
=> Fix clippy warnings for examples

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.8

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.9

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.10

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.11

Cargo.toml
=> Fix `example.path` in `Cargo.toml`

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.12

CHANGELOG.adoc, src/exit_code.rs
=> Add link to `true`

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.13

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.7.14

.github/dependabot.yml, .github/workflows/CI.yaml, CHANGELOG.adoc, Cargo.lock, Cargo.toml, README.md, clippy.toml, src/error.rs, src/exit_code/convert.rs, src/lib.rs
=> Add conversion methods for integers to `ExitCode`

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.8.0

.github/workflows/CI.yaml, CHANGELOG.adoc, Cargo.lock, Cargo.toml, README.md, clippy.toml, examples/cat.rs, examples/cmp.rs, examples/isutf8.rs
=> Rewrite examples using `clap`

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Update version to 0.8.1

CODE_OF_CONDUCT.md, LICENSES/CC-BY-4.0.txt
=> docs: Fix license for `CODE_OF_CONDUCT.md`

CHANGELOG.adoc, src/exit_code.rs, src/exit_code/consts.rs
=> feat: Add consts

README.md
=> docs(readme): Add similar projects section

.github/workflows/CI.yaml, CHANGELOG.adoc, benches/convert.rs, benches/exit_code.rs, benches/result.rs
=> test: Add benchmarks

.github/workflows/dependabot_auto_merge.yaml
=> ci: Add `dependabot_auto_merge.yaml`

CHANGELOG.adoc, benches/exit_code.rs, src/exit_code.rs
=> feat: Implement `Default` for `ExitCode`

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> chore(release): Update version to 0.8.3

src/exit_code.rs
=> test: Update doctests

CHANGELOG.adoc, src/exit_code.rs, src/exit_code/fmt.rs
=> feat: Add more formatters for `ExitCode`

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> chore(release): Update version to 0.8.4

src/error.rs, src/exit_code.rs
=> test: Add tests for `const fn`

.bumpversion.toml, CHANGELOG.adoc, CITATION.cff, Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> chore(release): Update version to 0.8.5

Cargo.toml
The `dependencies` table is empty so remove it.
Closes #
=> chore: Remove `dependencies` table

README.md, src/exit_code/convert.rs, src/lib.rs
=> test: Fix tests for `ErrorKind`

examples/cat.rs, src/exit_code.rs, src/exit_code/convert.rs, src/exit_code/fmt.rs, src/exit_code/result.rs
=> chore: Remove `allow`

src/lib.rs
=> chore: Update examples

src/exit_code/consts.rs
=> docs: Update description for constants
